### PR TITLE
Make it (hopefully) awesomer!

### PR DESCRIPTION
**Pull request by KevinLiddle**
I really liked this library, and I decided to fork it when mine stopped working. I say "mine", but I only forked the original from someone else and they deleted their account, so it only looks like I own it.
- I loved the way you could specify unicorn AND sparkle images 😍, but I wanted to use a bunch of random files without putting them in the `/.unicornleap/` directory, so I made those options configurable from any directory
- The leaping is now done in an animation transaction, which allows the loop to exit when the animation is done, rather than after a certain amount of time
  - this is a little weird, because I had to put more code than I wanted to in `main.swift`
- Adds options for eccentricity to let you specify how high your unicorn leaps!
  eccentricity
- Adds option for a crazier herd mode!
  herd-mode
- Also upgrades to Swift 3

Let me know if you like the changes or if you'd like to leave out some of them or all of them or whatever. Thanks for the great implementation!

### CODE REVIEW

**Comment by jgdavey** [comment]
I think this is awesome.

Which features require OS X 10.11? I'm on 10.10 still (meh upgrades) and wasn't able to compile.

**Comment by KevinLiddle** [comment]
I think only the last commit did the XCode automatic upgrade to Swift 3 syntax. If you checkout to https://github.com/jgdavey/unicornleap/pull/5/commits/eb7877345beae17e596527ddc5f81a79e156b418, does that work?

**Comment by jgdavey** [comment]
I'm on OS X 10.10.5 with XCode 7.x. I can compile the from eb7877345beae17e596527ddc5f81a79e156b418, but the unicorn never shows up. The program exits immediately.

I traced it back to the Animation Transaction loop. Is this a never API? Not sure why it compiled fine, and runs without error for me if so.

**Comment by KevinLiddle** [comment]
Interesting. According to the [docs](https://developer.apple.com/reference/quartzcore/catransaction), it should be available, but I don't know why it wouldn't animate. This is the most swift I've written and the only core animation I've ever done.

I was running this with XCode 7 before I upgraded to XCode 8 (and swift 3) on Friday, and it was all working fine, but maybe I borked something when I was organizing my commits. I'll look into it sometime this week and see if I can figure out what's wrong.

**Comment by KevinLiddle** [comment]
So I downloaded XCode 7.3.1 and 7.2.1 to try this out (pre-Swift-3 upgrade) and it compiled and ran fine for me. I'm not sure what the issue is, but maybe something with OSX 10.10.5 or maybe I need to try an XCode version down a patch level, but I'm not sure what the problem is. I couldn't find any similar bug reports anywhere either.

I'm a little stumped.

**Comment by jgdavey** [comment]
Yeah, it must have more to do with the version of OS X I’m running. It
works with Xcode 7 / 10.11 but not Xcode 7 / 10.10.5


On September 27, 2016 at 9:49:21 PM, Kevin Liddle (notifications@github.com)
wrote:

So I downloaded XCode 7.3.1 and 7.2.1 to try this out (pre-Swift-3 upgrade)
and it compiled and ran fine for me. I'm not sure what the issue is, but
maybe something with OSX 10.10.5 or maybe I need to try an XCode version
down a patch level, but I'm not sure what the problem is. I couldn't find
any similar bug reports anywhere either.

I'm a little stumped.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jgdavey/unicornleap/pull/5#issuecomment-250050620>, or mute
the thread

**Comment by jgdavey** [comment]
I've merged all but your last commit (Swift 3). I'm happy to talk about the merits of that one in a separate PR.

**Pull request closed without merging**
